.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH trellis-version-apply 1 "" trellis "Trellis Manual"
.SH NAME
trellis\-version\-apply \- Bump versions, render changelogs, patch manifest.toml locked versions
.SH SYNOPSIS
\fBtrellis version apply\fR [\fB\-C\fR|\fB\-\-directory\fR] [\fB\-\-json\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Bump versions, render changelogs, patch manifest.toml locked versions
.SH OPTIONS
.TP
\fB\-C\fR, \fB\-\-directory\fR \fI<DIR>\fR
Run as if started in this directory
.TP
\fB\-\-json\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
