.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH trellis-tag-plan 1 "" trellis "Trellis Manual"
.SH NAME
trellis\-tag\-plan \- List releasable packages whose current version has no tag yet
.SH SYNOPSIS
\fBtrellis tag plan\fR [\fB\-C\fR|\fB\-\-directory\fR] [\fB\-\-json\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
List releasable packages whose current version has no tag yet
.SH OPTIONS
.TP
\fB\-C\fR, \fB\-\-directory\fR \fI<DIR>\fR
Run as if started in this directory
.TP
\fB\-\-json\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
