.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH trellis-info 1 "" trellis "Trellis Manual"
.SH NAME
trellis\-info \- Show details for one package
.SH SYNOPSIS
\fBtrellis info\fR [\fB\-C\fR|\fB\-\-directory\fR] [\fB\-\-json\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIPACKAGE\fR> 
.SH DESCRIPTION
Show details for one package
.SH OPTIONS
.TP
\fB\-C\fR, \fB\-\-directory\fR \fI<DIR>\fR
Run as if started in this directory
.TP
\fB\-\-json\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIPACKAGE\fR>

