.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH trellis-ci-outputs 1 "" trellis "Trellis Manual"
.SH NAME
trellis\-ci\-outputs \- Emit workspace facts as key=value lines for $GITHUB_OUTPUT
.SH SYNOPSIS
\fBtrellis ci outputs\fR [\fB\-C\fR|\fB\-\-directory\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Emit workspace facts as key=value lines for $GITHUB_OUTPUT
.SH OPTIONS
.TP
\fB\-C\fR, \fB\-\-directory\fR \fI<DIR>\fR
Run as if started in this directory
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
