pub mod changelog;
pub mod ci;
pub mod doctor;
pub mod exec;
pub mod generate;
pub mod graph;
pub mod info;
pub mod init;
pub mod list;
pub mod lockfile;
pub mod pin;
pub mod publish;
pub mod release;
pub mod run;
pub mod tag;
pub mod version;
pub mod version_override;

use clap::CommandFactory;

/// Render the whole command tree as a Starlight `.md` page, straight from the
/// clap definition, so the website's CLI reference can never drift from the
/// actual flags. `trellis markdown-help` prints exactly this; a test asserts
/// the checked-in page (`website/src/content/docs/docs/reference.md`) matches
/// it byte-for-byte. It's a plain `.md`, not `.mdx`: some help strings contain
/// `{`/`}`, which MDX would try to evaluate.
pub fn markdown_help() -> String {
    let body = clap_markdown::help_markdown_custom::<crate::Cli>(
        &clap_markdown::MarkdownOptions::new().show_footer(false),
    );
    // Replace the flat overview, but keep every generated command section.
    let (_, body) = body
        .split_once("\n## ")
        .expect("clap-markdown must render command headings");
    let cli = crate::Cli::command();
    let groups: &[(&str, &[&str])] = &[
        ("Workspace tasks", &["run", "exec", "list", "graph", "info"]),
        (
            "Releases",
            &["changelog", "version", "release", "tag", "publish"],
        ),
        ("Setup and checks", &["init", "doctor", "pin", "lockfile"]),
        ("Automation", &["ci", "completions"]),
    ];
    let mut index = String::from(
        "## Find a command\n\n\
         For global flags, see <a href=\"#trellis\"><code>trellis</code></a>.\n\n\
         <nav class=\"task_index\" aria-label=\"Command topics\">\n",
    );
    for (label, names) in groups {
        index.push_str(&format!(
            "<div>\n<p class=\"task_index_label\">{label}</p>\n<ul>\n"
        ));
        for name in *names {
            let command = cli
                .get_subcommands()
                .find(|command| command.get_name() == *name)
                .expect("command index entries must exist in the CLI");
            command_index_entries(command, name, &mut index);
        }
        index.push_str("</ul>\n</div>\n");
    }
    index.push_str("</nav>\n\n");
    format!(
        "---\n\
         title: CLI reference\n\
         description: Every trellis command, flag, and argument — generated from the CLI itself.\n\
         ---\n\
         \n\
         <!-- Generated by `trellis markdown-help`; do not edit by hand. -->\n\
         \n\
         {index}## {}",
        body.trim_end()
    ) + "\n"
}

fn command_index_entries(command: &clap::Command, path: &str, index: &mut String) {
    if command.is_hide_set() {
        return;
    }
    let anchor = path.replace(' ', "-");
    index.push_str(&format!(
        "<li><a href=\"#trellis-{anchor}\"><code>{path}</code></a></li>\n"
    ));
    for child in command.get_subcommands() {
        command_index_entries(child, &format!("{path} {}", child.get_name()), index);
    }
}
