pub mod changelog;
pub mod ci;
pub mod doctor;
pub mod exec;
pub mod graph;
pub mod info;
pub mod list;
pub mod lockfile;
pub mod new;
pub mod publish;
pub mod release;
pub mod run;
pub mod tag;
pub mod version;

use crate::workspace::Workspace;
use serde_json::json;

/// Render the whole command tree as a Starlight `.md` page, straight from the
/// clap definition, so the website's CLI reference can never drift from the
/// actual flags. `trellis markdown-help` prints exactly this; a test asserts
/// the checked-in page (`website/src/content/docs/docs/reference.md`) matches
/// it byte-for-byte. It's a plain `.md` (not `.mdx`) on purpose: some help
/// strings contain `{`/`}`, which MDX would try to evaluate.
pub fn markdown_help() -> String {
    let body = clap_markdown::help_markdown_custom::<crate::Cli>(
        &clap_markdown::MarkdownOptions::new().show_footer(false),
    );
    // Drop clap-markdown's own H1 and intro line; the Starlight frontmatter
    // supplies the page title, and a second H1 would double the heading.
    let body = body
        .find("**Command Overview:**")
        .map(|idx| &body[idx..])
        .unwrap_or(&body);
    format!(
        "---\n\
         title: CLI reference\n\
         description: Every trellis command, flag, and argument — generated from the CLI itself.\n\
         ---\n\
         \n\
         <!-- Generated by `trellis markdown-help`; do not edit by hand. -->\n\
         \n\
         {}",
        body.trim_end()
    ) + "\n"
}

/// The JSON shape shared by `list --json` and `info --json`.
pub fn member_json(workspace: &Workspace, idx: usize) -> serde_json::Value {
    let member = &workspace.members[idx];
    json!({
        "name": member.name,
        "version": member.version(),
        "path": member.rel_path,
        "releasable": member.releasable,
        "dependencies": workspace
            .deps_of(idx)
            .iter()
            .map(|&dep| workspace.members[dep].name.clone())
            .collect::<Vec<_>>(),
        "dependents": workspace
            .dependents_of(idx)
            .iter()
            .map(|&dep| workspace.members[dep].name.clone())
            .collect::<Vec<_>>(),
    })
}
