pub mod changelog;
pub mod ci;
pub mod doctor;
pub mod exec;
pub mod generate;
pub mod graph;
pub mod info;
pub mod init;
pub mod list;
pub mod lockfile;
pub mod pin;
pub mod publish;
pub mod release;
pub mod run;
pub mod tag;
pub mod version;
pub mod version_override;

/// Render the whole command tree as a Starlight `.md` page, straight from the
/// clap definition, so the website's CLI reference can never drift from the
/// actual flags. `trellis markdown-help` prints exactly this; a test asserts
/// the checked-in page (`website/src/content/docs/docs/reference.md`) matches
/// it byte-for-byte. It's a plain `.md`, not `.mdx`: some help strings contain
/// `{`/`}`, which MDX would try to evaluate.
pub fn markdown_help() -> String {
    let body = clap_markdown::help_markdown_custom::<crate::Cli>(
        &clap_markdown::MarkdownOptions::new().show_footer(false),
    );
    // Drop clap-markdown's own H1 and intro line; the Starlight frontmatter
    // supplies the page title, and a second H1 would double the heading.
    let body = body
        .find("**Command Overview:**")
        .map_or(body.as_str(), |idx| &body[idx..]);
    format!(
        "---\n\
         title: CLI reference\n\
         description: Every trellis command, flag, and argument — generated from the CLI itself.\n\
         ---\n\
         \n\
         <!-- Generated by `trellis markdown-help`; do not edit by hand. -->\n\
         \n\
         {}",
        body.trim_end()
    ) + "\n"
}
