//! Interop with changie (https://changie.dev), the changelog fragment tool.
//! Trellis generates the mechanical part of `.changie.yaml` — the `projects:`
//! section — from the workspace model, and shells out to changie for
//! `new`/`next`/`batch`/`merge`. The fragment format stays changie-native.

use crate::workspace::Workspace;
use anyhow::{Context, Result, bail};
use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use std::process::Command;

pub const CONFIG_FILE: &str = ".changie.yaml";

/// Where changie keeps its things, read from `.changie.yaml` when present
/// (falling back to changie's defaults).
pub struct ChangieEnv {
    pub unreleased_dir: PathBuf,
}

pub fn locate(root: &Path) -> ChangieEnv {
    let (changes_dir, unreleased_dir) = match std::fs::read_to_string(root.join(CONFIG_FILE)) {
        Ok(text) => (
            top_level_string(&text, "changesDir").unwrap_or_else(|| ".changes".to_string()),
            top_level_string(&text, "unreleasedDir").unwrap_or_else(|| "unreleased".to_string()),
        ),
        Err(_) => (".changes".to_string(), "unreleased".to_string()),
    };
    ChangieEnv {
        unreleased_dir: root.join(changes_dir).join(unreleased_dir),
    }
}

/// Read a top-level `key: value` scalar from a YAML document without a YAML
/// dependency. Good enough for changie's flat config keys.
fn top_level_string(text: &str, key: &str) -> Option<String> {
    text.lines().find_map(|line| {
        let value = line.strip_prefix(key)?.trim_start().strip_prefix(':')?;
        let value = value.trim().trim_matches(['"', '\'']);
        (!value.is_empty()).then(|| value.to_string())
    })
}

/// Unreleased changelog fragments, grouped by their `project:` key.
#[derive(Debug, Default)]
pub struct Fragments {
    pub by_project: BTreeMap<String, usize>,
    /// Fragment files with no `project:` key — invalid in a projects-mode
    /// workspace, since changie cannot route them to a changelog.
    pub missing_project: Vec<String>,
}

pub fn unreleased_fragments(env: &ChangieEnv) -> Result<Fragments> {
    let mut fragments = Fragments::default();
    let entries = match std::fs::read_dir(&env.unreleased_dir) {
        Ok(entries) => entries,
        Err(_) => return Ok(fragments), // no unreleased dir yet
    };
    for entry in entries {
        let path = entry?.path();
        let is_yaml = path
            .extension()
            .is_some_and(|ext| ext == "yaml" || ext == "yml");
        if !is_yaml {
            continue;
        }
        let text = std::fs::read_to_string(&path)
            .with_context(|| format!("failed to read {}", path.display()))?;
        match top_level_string(&text, "project") {
            Some(project) => *fragments.by_project.entry(project).or_insert(0) += 1,
            None => fragments.missing_project.push(
                path.file_name()
                    .unwrap_or_default()
                    .to_string_lossy()
                    .into_owned(),
            ),
        }
    }
    Ok(fragments)
}

const GENERATED_MARKER: &str =
    "  # Generated by `trellis changelog sync` from workspace.toml — do not edit by hand.";

/// The `projects:` section derived from the workspace model: one block per
/// releasable member (ignore-release matches get none).
pub fn projects_block(workspace: &Workspace) -> String {
    let mut out = String::from("projects:\n");
    out.push_str(GENERATED_MARKER);
    out.push('\n');
    for member in workspace.members.iter().filter(|m| m.releasable) {
        out.push_str(&format!(
            concat!(
                "  - label: {name}\n",
                "    key: {name}\n",
                "    changelog: {path}/CHANGELOG.md\n",
                "    replacements:\n",
                "      - path: {path}/gleam.toml\n",
                "        find: 'version = \".*\"'\n",
                "        replace: 'version = \"{{{{.VersionNoPrefix}}}}\"'\n",
            ),
            name = member.name,
            path = member.rel_path,
        ));
    }
    out
}

/// Replace (or append) the top-level `projects:` section of a `.changie.yaml`,
/// leaving everything else — including comments — untouched. The section ends
/// at the next top-level key.
pub fn splice_projects(existing: &str, block: &str) -> String {
    let lines: Vec<&str> = existing.lines().collect();
    let start = lines
        .iter()
        .position(|line| *line == "projects:" || line.starts_with("projects:"));
    let Some(start) = start else {
        let mut out = existing.trim_end().to_string();
        if !out.is_empty() {
            out.push_str("\n\n");
        }
        out.push_str(block);
        return out;
    };
    let end = lines[start + 1..]
        .iter()
        .position(|line| {
            line.chars()
                .next()
                .is_some_and(|c| c.is_ascii_alphabetic() || c == '_' || c == '"' || c == '\'')
        })
        .map(|offset| start + 1 + offset)
        .unwrap_or(lines.len());

    let mut out = String::new();
    for line in &lines[..start] {
        out.push_str(line);
        out.push('\n');
    }
    out.push_str(block.trim_end());
    out.push('\n');
    for line in &lines[end..] {
        out.push_str(line);
        out.push('\n');
    }
    out
}

/// A complete starter `.changie.yaml` for workspaces adopting changie through
/// trellis. The kinds/formats are conventional; the projects section is
/// generated. The version separator is derived from `tag-format` so changie's
/// per-project versions match trellis tags.
pub fn starter_config(workspace: &Workspace) -> String {
    let separator = version_separator(&workspace.config.publish.tag_format);
    let mut out = format!(
        concat!(
            "changesDir: .changes\n",
            "unreleasedDir: unreleased\n",
            "changelogPath: CHANGELOG.md\n",
            "versionExt: md\n",
            "versionFormat: '## {{{{.Version}}}} - {{{{.Time.Format \"2006-01-02\"}}}}'\n",
            "kindFormat: '### {{{{.Kind}}}}'\n",
            "changeFormat: '* {{{{.Body}}}}'\n",
            "projectsVersionSeparator: \"{separator}\"\n",
            "kinds:\n",
            "  - label: Added\n",
            "    auto: minor\n",
            "  - label: Changed\n",
            "    auto: major\n",
            "  - label: Deprecated\n",
            "    auto: minor\n",
            "  - label: Removed\n",
            "    auto: major\n",
            "  - label: Fixed\n",
            "    auto: patch\n",
            "  - label: Security\n",
            "    auto: patch\n",
            "\n",
        ),
        separator = separator,
    );
    out.push_str(&projects_block(workspace));
    out
}

/// The text between `{name}` and `{version}` in the tag format — e.g.
/// `{name}-v{version}` → `-v` — falling back to changie's default `/`.
fn version_separator(tag_format: &str) -> String {
    tag_format
        .strip_prefix("{name}")
        .and_then(|rest| rest.strip_suffix("{version}"))
        .filter(|sep| !sep.is_empty() && !sep.contains(['{', '}']))
        .map(str::to_string)
        .unwrap_or_else(|| "/".to_string())
}

fn changie_bin() -> String {
    // Overridable so tests (and unusual installs) can point at a specific
    // binary.
    std::env::var("TRELLIS_CHANGIE_BIN").unwrap_or_else(|_| "changie".to_string())
}

/// Run changie capturing stdout (for `next`, `batch`, `merge`).
pub fn run(root: &Path, args: &[&str]) -> Result<String> {
    let bin = changie_bin();
    let output = Command::new(&bin)
        .args(args)
        .current_dir(root)
        .output()
        .with_context(|| format!("failed to run `{bin}` — is changie installed?"))?;
    if !output.status.success() {
        bail!(
            "`{bin} {}` failed: {}",
            args.join(" "),
            String::from_utf8_lossy(&output.stderr).trim()
        );
    }
    Ok(String::from_utf8_lossy(&output.stdout).into_owned())
}

/// Run changie interactively (for `new`, which prompts).
pub fn run_interactive(root: &Path, args: &[&str]) -> Result<()> {
    let bin = changie_bin();
    let status = Command::new(&bin)
        .args(args)
        .current_dir(root)
        .status()
        .with_context(|| format!("failed to run `{bin}` — is changie installed?"))?;
    if !status.success() {
        bail!("`{bin} {}` failed", args.join(" "));
    }
    Ok(())
}

/// Parse the version out of `changie next` output, which may carry a project
/// prefix and/or a `v` prefix (`lat_core-v1.3.0`, `v1.3.0`, `1.3.0`).
pub fn parse_next_version(stdout: &str) -> Result<semver::Version> {
    let raw = stdout.trim();
    let start = raw
        .char_indices()
        .find_map(|(idx, c)| c.is_ascii_digit().then_some(idx))
        .with_context(|| format!("no version in changie output `{raw}`"))?;
    semver::Version::parse(&raw[start..])
        .with_context(|| format!("cannot parse version from changie output `{raw}`"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn top_level_string_reads_flat_keys() {
        let text = "changesDir: .changes\nunreleasedDir: 'pending'\nproject: \"lat_core\"\n";
        assert_eq!(
            top_level_string(text, "changesDir").as_deref(),
            Some(".changes")
        );
        assert_eq!(
            top_level_string(text, "unreleasedDir").as_deref(),
            Some("pending")
        );
        assert_eq!(
            top_level_string(text, "project").as_deref(),
            Some("lat_core")
        );
        assert_eq!(top_level_string(text, "missing"), None);
    }

    #[test]
    fn splice_replaces_existing_projects_section() {
        let existing = "changesDir: .changes\n# a comment\nprojects:\n  - label: old\n    key: old\nkinds:\n  - label: Added\n";
        let spliced = splice_projects(existing, "projects:\n  - label: new\n    key: new\n");
        assert!(spliced.contains("# a comment"));
        assert!(spliced.contains("key: new"));
        assert!(!spliced.contains("key: old"));
        assert!(spliced.contains("kinds:"));
        // idempotent
        assert_eq!(
            splice_projects(&spliced, "projects:\n  - label: new\n    key: new\n"),
            spliced
        );
    }

    #[test]
    fn splice_appends_when_no_projects_section() {
        let spliced = splice_projects("changesDir: .changes\n", "projects:\n  - key: a\n");
        assert!(spliced.starts_with("changesDir: .changes\n\n"));
        assert!(spliced.ends_with("projects:\n  - key: a\n"));
    }

    #[test]
    fn parses_next_version_variants() {
        for (input, expected) in [
            ("1.3.0", (1, 3, 0)),
            ("v1.3.0\n", (1, 3, 0)),
            ("lat_core-v2.0.0", (2, 0, 0)),
            ("lat_core/v0.5.1", (0, 5, 1)),
        ] {
            let version = parse_next_version(input).unwrap();
            assert_eq!(
                (version.major, version.minor, version.patch),
                (expected.0, expected.1, expected.2),
                "input: {input}"
            );
        }
        assert!(parse_next_version("no version here").is_err());
    }

    #[test]
    fn version_separator_derived_from_tag_format() {
        assert_eq!(version_separator("{name}-v{version}"), "-v");
        assert_eq!(version_separator("{name}/{version}"), "/");
        assert_eq!(version_separator("release-{version}"), "/"); // no {name} prefix
    }
}
